### ISSUE TITLE
Failed to get execution log: java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by NFDWADM** [ajrnz/rundeck-telegram-plugin#11]
I am trying to have a log file send when a job fails, but that fails with:

>-01 13:45:25,581] web.requests "GET /menu/homeAjax" 172.30.92.168 https nohdke form 13 ? [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)

>[2019-07-01 13:45:25,602] web.requests "GET /tour/listAll" 172.30.92.168 https nohdke form 5 ? [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)

>[2019-07-01 13:45:25,767] web.requests "GET /execution/ajaxExecState/232" 172.30.92.168 https nohdke form 52 ? [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)

>[2019-07-01 13:45:25,859] web.requests "GET /static/images/icon-tiny-disclosure-waiting.gif" 172.30.92.168 https  form 4 ? [image/gif] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)

>[2019-07-01 13:45:26,373] web.requests "GET /static/images/icon-tiny-disclosure-waiting.gif" 172.30.92.168 https  form 3 ? [image/gif] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)

>**Failed to get execution log: java.net.SocketTimeoutException: connect timed out**`

I do receive a Telegram message (correctly formatted), just no logfile. The API is correct, I triple checked.

Any ideas what I could try?

rundeck 3.0.21.

**Comment by NFDWADM** [comment]
I think I cut the log file to early. These lines appear immediately after the ones above in the log:


>[2019-07-01 13:45:27,388] web.requests "GET /execution/ajaxExecState/232" 172.30.92.168 https nohdke form 16 ? [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)


>[2019-07-01 13:45:33,490] web.requests "POST /execution/tailExecutionOutput" 172.30.92.168 https nohdke form 148 ? [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170)`

"/execution/tailExecutionOutput/**232**" does return an XML formatted log file. Is the timeout maybe too low? Or is it because the job id doesn't appear in "POST /execution/tailExecutionOutput"?

**Comment by NFDWADM** [comment]
Update: I think now this is because of my docker container not being able to reach the host containers ports.

**Comment by ajrnz** [comment]
Sounds likely that that is the issue. Thanks for following up.
