### ISSUE TITLE
Failed to send telegram when running Rundeck on SSL (HTTPS)

### ISSUE THREAD

**Issue by MLukman** [ajrnz/rundeck-telegram-plugin#3]
In /var/log/rundeck/service.log:

```
Failed to send Telegram message: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Running Rundeck 2.7.1 on docker using https://hub.docker.com/r/jordan/rundeck/

I managed to resolved it by manually importing SSL certificate from api.telegram.org using the following steps:

```
echo | openssl s_client -connect api.telegram.org:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > api-telegram-org.pub
keytool -import -file api-telegram-org.pub -alias api-telegram-org -keystore /etc/rundeck/ssl/truststore
/etc/init.d/rundeckd restart
```

But I wonder if this can be done automatically upon Rundeck installing the plugin the first time.

**Comment by ajrnz** [comment]
I think this is likely to be a problem with a proxy, the machine ca certificates or the java setup on the machine. Either way it's not a plugins responsibility to manage certificates so I'm going to close.
