### ISSUE TITLE
proxy settings via env

### ISSUE THREAD

**Issue by freeseacher** [ajrnz/rundeck-telegram-plugin#5]
Please add support for proxy with auth and switch to standard proxy settings approach

currently i have standard proxy environment http_proxy/https_proxy. 
by default i can provide such an url
```
      export {http,https,ftp}_proxy="http://user:pass@proxy:port/"
      export no_proxy=localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
```
Please switch to that method for setting up proxy.

**Comment by supnobita** [comment]
I have the same problem :(
but I use sbt to rebuild this lib after modifing those line:
In file: ./rundeck-telegram-plugin/src/main/scala/ajr/rundeck/telegram/TelegramMessenger.scala:14: 
   val request = http(url).proxy('proxy', port).params(params).asString
It work for me. 
I don't know anything about scala, so i can not add proxy via variables in config file (telegram.properties),  just hard code it . Haizzz

**Comment by ajrnz** [comment]
You should be able to set these using `Project Settings -> Edit Configuration` in Rundeck and adding something like:

    project.plugin.Notification.TelegramNotification.proxyHost=<host>
    project.plugin.Notification.TelegramNotification.proxyPort=<port>
