### ISSUE TITLE
Failed do send Message: javax.net.ssl.SSLException

### ISSUE THREAD

**Issue by highsinnc** [ajrnz/rundeck-telegram-plugin#7]
Hello, I got an error while trying to send telegram message:

`Failed to send Telegram message: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

full log: [log.txt](https://github.com/ajrnz/rundeck-telegram-plugin/files/2607878/log.txt)

Rundeck 3.0.8 on windows with version 1.0.6 of the plugin.
Can you help me make this work?

Thanks.

**Comment by ajrnz** [comment]
I think this is likely to be an issue with your java installation or machine certificates.
I'm not an SSL expert so I can't give you much advice. This seems like a common problem:

https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

maybe you can find some help there.
